# Generated by Django 5.0.2 on 2024-03-04 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('client', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('url', models.CharField(max_length=100000)),
                ('text', models.TextField()),
                ('picture1', models.ImageField(upload_to='media')),
                ('picture2', models.ImageField(blank=True, null=True, upload_to='media')),
                ('picture3', models.ImageField(blank=True, null=True, upload_to='media')),
                ('picture4', models.ImageField(blank=True, null=True, upload_to='media')),
                ('picture5', models.ImageField(blank=True, null=True, upload_to='media')),
                ('picture6', models.ImageField(blank=True, null=True, upload_to='media')),
                ('picture7', models.ImageField(blank=True, null=True, upload_to='media')),
                ('picture8', models.ImageField(blank=True, null=True, upload_to='media')),
                ('picture9', models.ImageField(blank=True, null=True, upload_to='media')),
                ('picture10', models.ImageField(blank=True, null=True, upload_to='media')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfolder.type')),
            ],
        ),
    ]
